/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package POS_TokoKelontong;

import java.sql.Connection;
import java.sql.Statement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class FormBarang extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormBarang
     */
    public FormBarang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtkdbrg = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtnmbrg = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtstok = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        Optbaru = new javax.swing.JRadioButton();
        Optedit = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        cmdsimpan = new javax.swing.JButton();
        cmdhapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        grdbrg = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("Kode Barang");

        jLabel2.setText("Nama Barang");

        jLabel3.setText("Harga");

        jLabel4.setText("Stok");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtkdbrg)
                    .addComponent(txtnmbrg)
                    .addComponent(txtharga)
                    .addComponent(txtstok, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtkdbrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtnmbrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtstok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        buttonGroup1.add(Optbaru);
        Optbaru.setText("Baru");
        Optbaru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OptbaruMouseClicked(evt);
            }
        });
        Optbaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OptbaruActionPerformed(evt);
            }
        });

        buttonGroup1.add(Optedit);
        Optedit.setText("Edit");
        Optedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OpteditMouseClicked(evt);
            }
        });
        Optedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpteditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Optbaru)
                    .addComponent(Optedit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Optbaru)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Optedit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        cmdsimpan.setText("Simpan");
        cmdsimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdsimpanMouseClicked(evt);
            }
        });

        cmdhapus.setText("Hapus");
        cmdhapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdhapusMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(cmdsimpan)
                .addGap(18, 18, 18)
                .addComponent(cmdhapus)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdsimpan)
                    .addComponent(cmdhapus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        grdbrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        grdbrg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grdbrgMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(grdbrg);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String koneksi = "jdbc:mysql://localhost/dbpenjualan";
    String user = "root";
    String pass = "";
    Connection connection;
    Statement statement;

    private void nourut() {
        try {
            String sql = "select right (kdbrg,3) as no_terakhir from tb_barang order by kdbrg";
            ResultSet rs = statement.executeQuery(sql);
            if (rs.first() == false) {
                txtkdbrg.setText("BG001");
            } else {
                rs.last();
                int no = rs.getInt(1) + 1;
                String cno = String.valueOf(no);
                int pjg_cno = cno.length();
                for (int i = 0; i < 3 - pjg_cno; i++) {
                    cno = "0" + cno;
                }
                txtkdbrg.setText("BG" + cno);
            }
        } catch (Exception DBException) {
            System.err.println("error :" + DBException);
        }
    }

    private void bersih() {
        nourut();
        txtnmbrg.setText("");
        txtharga.setText("0");
        txtstok.setText("0");
        txtnmbrg.requestFocus();
        Optbaru.setSelected(true);
        Optedit.setSelected(false);
        cmdhapus.setEnabled(false);
        cmdsimpan.setEnabled(true);

        try {
//            connection = DriverManager.getConnection(koneksi, user, pass);
//            statement = connection.createStatement();
            String sql = "select * from tb_barang";
            ResultSet rs = statement.executeQuery(sql);
            final String[] headers = {"Kode", "Nama", "Harga", "Stok"};
            rs.last();
            int n = rs.getRow();
            Object[][] data = new Object[n][4];
            int p = 0;
            rs.beforeFirst();
            while (rs.next()) {

                data[p][0] = rs.getString(1);
                data[p][1] = rs.getString(2);
                data[p][2] = rs.getString(3);
                data[p][3] = rs.getString(4);
                p++;
            grdbrg.setModel(new javax.swing.table.DefaultTableModel(data,headers));
            grdbrg.setAlignmentX(CENTER_ALIGNMENT);
            }
        } catch (Exception DBException) {
            System.err.println("Error :" + DBException);
        }
    }
    private void OptbaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OptbaruActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OptbaruActionPerformed

    private void OpteditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpteditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_OpteditActionPerformed

    private void cmdsimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdsimpanMouseClicked
        // TODO add your handling code here:
        if (cmdsimpan.isEnabled() == false) {
            return;
        }

        try {
            String sql;
//            connection = DriverManager.getConnection(koneksi, user, pass);
//            statement = connection.createStatement();
            if (Optbaru.isSelected()) {
                sql = "insert into tb_barang values ('";
                sql += txtkdbrg.getText() + "','";
                sql += txtnmbrg.getText() + "','";
                sql += txtharga.getText() + "','";
                sql += txtstok.getText() + "')";
            } else {
                sql = "update tb_barang set nmbrg='";
                sql += txtnmbrg.getText() + "',harga='";
                sql += txtharga.getText() + "',stok='";
                sql += txtstok.getText() + "' ";
                sql += "where kdbrg='" + txtkdbrg.getText() + "'";
            }
            statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Simpan / Update Data Berhasil", "Informasi", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception DBException) {
            JOptionPane.showMessageDialog(this, "Simpan / Update Data Gagal", "Error", JOptionPane.ERROR_MESSAGE);
            System.err.println("Error : " + DBException);
        }
        bersih();
    }//GEN-LAST:event_cmdsimpanMouseClicked

    private void cmdhapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdhapusMouseClicked
        // TODO add your handling code here:
        if(cmdhapus.isEnabled() == false)
        {
            return;
        }
        
        try
        {
            String sql="delete from tb_barang where kdbrg='" + txtkdbrg.getText() + "'";
            statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Hapus Data Berhasil...", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            
        }
        catch (Exception DBException) {
            JOptionPane.showMessageDialog(this, "Hapus Data Gagal...", "Error", JOptionPane.ERROR_MESSAGE);
           System.err.println("Error : " + DBException );
        }
        bersih();
    }//GEN-LAST:event_cmdhapusMouseClicked

    private void OptbaruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OptbaruMouseClicked
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_OptbaruMouseClicked

    private void OpteditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OpteditMouseClicked
        // TODO add your handling code here:
        if (grdbrg.getRowCount() < 1) {
            JOptionPane.showMessageDialog(this, "Tidak ada data untuk diedit...", "Peringatan", JOptionPane.WARNING_MESSAGE );
            bersih();
        } 
    }//GEN-LAST:event_OpteditMouseClicked

    private void grdbrgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grdbrgMouseClicked
        // TODO add your handling code here:
        if (Optedit.isSelected()) {
            txtkdbrg.setText(grdbrg.getValueAt(grdbrg.getSelectedRow(), 0).toString());
            txtnmbrg.setText(grdbrg.getValueAt(grdbrg.getSelectedRow(), 1).toString());
            txtharga.setText(grdbrg.getValueAt(grdbrg.getSelectedRow(), 2).toString());
            txtstok.setText(grdbrg.getValueAt(grdbrg.getSelectedRow(), 3).toString());
            cmdhapus.setEnabled(true);
        }
    }//GEN-LAST:event_grdbrgMouseClicked

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            koneksi = "jdbc:mysql://localhost/dbpenjualan";
            connection = DriverManager.getConnection(koneksi, user, pass);
            statement = connection.createStatement();

        } catch (Exception DBException) {
            JOptionPane.showMessageDialog(this, "Koneksi Gagal", "Error", JOptionPane.ERROR_MESSAGE);
            System.err.println("Error" + DBException);
        }
        bersih();
    }//GEN-LAST:event_formInternalFrameOpened
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Optbaru;
    private javax.swing.JRadioButton Optedit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cmdhapus;
    private javax.swing.JButton cmdsimpan;
    private javax.swing.JTable grdbrg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtkdbrg;
    private javax.swing.JTextField txtnmbrg;
    private javax.swing.JTextField txtstok;
    // End of variables declaration//GEN-END:variables
}
