/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package POS_TokoKelontong;

import static java.awt.Component.CENTER_ALIGNMENT;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Properties;
import javax.swing.JOptionPane;

/**
 *
 * @author chirz
 */
public class FormPenjualan extends javax.swing.JInternalFrame {

    /**
     * Creates new form FormPenjualan
     */
    public FormPenjualan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnotran = new javax.swing.JTextField();
        txttgltran = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtkdbrg = new javax.swing.JTextField();
        cmdcrbrg = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtharga = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtnmbrg = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmdaddbrg = new javax.swing.JButton();
        cmddelbrg = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        txtjmljual = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        grdbrg = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txttotbyr = new javax.swing.JTextField();
        optbaru = new javax.swing.JRadioButton();
        optedit = new javax.swing.JRadioButton();
        cmdsimpan = new javax.swing.JButton();
        cmdhapus = new javax.swing.JButton();
        txtstok = new javax.swing.JTextField();

        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Data Penjualan");

        jLabel2.setText("No. Transaksi");

        jLabel3.setText("Tanggal Transaksi");

        jLabel4.setText("Kode Barang");

        cmdcrbrg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmdcrbrg.setText("Cari Barang");
        cmdcrbrg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdcrbrgMouseClicked(evt);
            }
        });

        jLabel5.setText("Harga Barang");

        jLabel6.setText("Nama Barang");

        jLabel7.setText("Stok");

        cmdaddbrg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmdaddbrg.setText("Tambah Barang");
        cmdaddbrg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdaddbrgMouseClicked(evt);
            }
        });

        cmddelbrg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmddelbrg.setText("Hapus Barang");
        cmddelbrg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmddelbrgMouseClicked(evt);
            }
        });

        jLabel8.setText("Jumlah Jual");

        txtjmljual.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtjmljualFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtjmljualFocusLost(evt);
            }
        });
        txtjmljual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtjmljualKeyReleased(evt);
            }
        });

        grdbrg.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(grdbrg);

        jLabel9.setText("Total Bayar");

        buttonGroup1.add(optbaru);
        optbaru.setText("Baru");
        optbaru.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                optbaruMouseClicked(evt);
            }
        });

        buttonGroup1.add(optedit);
        optedit.setText("Edit");
        optedit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opteditMouseClicked(evt);
            }
        });

        cmdsimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmdsimpan.setText("Simpan");
        cmdsimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdsimpanMouseClicked(evt);
            }
        });

        cmdhapus.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cmdhapus.setText("Hapus");
        cmdhapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cmdhapusMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(optbaru)
                            .addComponent(optedit))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmdsimpan)
                        .addGap(54, 54, 54)
                        .addComponent(cmdhapus)
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txttotbyr)
                                    .addGap(1, 1, 1))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtnotran, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(txtnmbrg, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtkdbrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(cmdcrbrg))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(cmdaddbrg)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cmddelbrg)))
                                    .addGap(15, 15, 15)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel8))
                                            .addGap(26, 26, 26)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(txtjmljual, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                                .addComponent(txtstok)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel5)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(txtharga))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel3)
                                                .addGap(18, 18, 18)
                                                .addComponent(txttgltran, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 16, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(213, 213, 213))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtnotran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttgltran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtkdbrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdcrbrg)
                    .addComponent(jLabel5)
                    .addComponent(txtharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtnmbrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtstok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdaddbrg)
                    .addComponent(cmddelbrg)
                    .addComponent(jLabel8)
                    .addComponent(txtjmljual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txttotbyr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(optbaru)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(optedit))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmdsimpan)
                            .addComponent(cmdhapus))))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String koneksi = "jdbc:mysql://localhost/dbpenjualan";
    String user = "root";
    String pass = "";
    Connection connection;
    Statement statement;
    float ctotbyr = 0;

    private void bersih() {
        txttgltran.setText("");
        DateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        java.util.Date date = new java.util.Date();
        txttgltran.setText(dateFormat.format(date));
        nourut();
        txtkdbrg.setText("");
        txtnmbrg.setText("");
        txtharga.setText("0");
        txtstok.setText("0");
        txtjmljual.setText("0");
        txttotbyr.setText("0");
        cmdcrbrg.requestFocus();
        optbaru.setSelected(true);
        optedit.setSelected(false);
        cmdhapus.setEnabled(false);
        cmdsimpan.setEnabled(false);
        cmdaddbrg.setEnabled(false);
        cmddelbrg.setEnabled(false);

        try {
            String sql = "select * from tb_barang";
            ResultSet rs = statement.executeQuery(sql);
            final String[] headers = {"Kode Barang", "Nama Barang", "Harga", "Jumlah Jual"};
            Object[][] data = new Object[0][4];
            grdbrg.setModel(new javax.swing.table.DefaultTableModel(data, headers));
//            int p = 0;
//            rs.beforeFirst();
//            while (rs.next()) {
//
//                data[p][0] = rs.getString(1);
//                data[p][1] = rs.getString(2);
//                data[p][2] = rs.getString(3);
//                data[p][3] = rs.getString(4);
//                p++;
//                grdbrg.setModel(new javax.swing.table.DefaultTableModel(data, headers));
//                grdbrg.setAlignmentX(CENTER_ALIGNMENT);
//            }
        } catch (Exception DBException) {
            System.err.println("Error :" + DBException);
        }
    }

    private void nourut() {
        try {
            String sql = "select right(notran,3) as no_terakhir from tb_penjualan where tgltran='" + txttgltran.getText() + "' order by notran";
            ResultSet rs = statement.executeQuery(sql);
            if (rs.first() == false) {
                txtnotran.setText("T" + txttgltran.getText().substring(8) + txttgltran.getText().substring(5, 7) + txttgltran.getText().substring(2, 4) + "001");
            } else {
                rs.last();
                int no = rs.getInt(1) + 1;
                String cno = String.valueOf(no);
                int pjg_cno = cno.length();
                for (int i = 0; i < 3 - pjg_cno; i++) {
                    cno = "0" + cno;
                }
                txtnotran.setText("T" + txttgltran.getText().substring(8) + txttgltran.getText().substring(5, 7) + txttgltran.getText().substring(2, 4) + cno);
            }
        } catch (Exception DBException) {
            System.out.println("Error : " + DBException);
        }
    }

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            connection = DriverManager.getConnection(koneksi, user, pass);
            statement = connection.createStatement();

        } catch (Exception DBException) {
            JOptionPane.showMessageDialog(this, "Koneksi Gagal", "Error", JOptionPane.ERROR_MESSAGE);
            System.err.println("Error" + DBException);
        }
        bersih();
    }//GEN-LAST:event_formInternalFrameOpened

    private void cmdcrbrgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdcrbrgMouseClicked
        // TODO add your handling code here:
        cariBarang dialog = new cariBarang(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
        Properties p = new Properties();
        try {
            FileInputStream in = new FileInputStream("barang.properties");
            p.load(in);
            in.close();
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        txtkdbrg.setText(p.getProperty("pkdbrg"));
        txtnmbrg.setText(p.getProperty("pnmbrg"));
        txtharga.setText(p.getProperty("pharga"));
        txtstok.setText(p.getProperty("pstok"));
        int cstok = 0;
        for (int i = 0; i < grdbrg.getRowCount(); i++) {
            String ckdbrg = grdbrg.getValueAt(i, 0).toString();
            if (txtkdbrg.getText().equals(ckdbrg)) {
                cstok = Integer.parseInt(grdbrg.getValueAt(i, 3).toString());
            }
        }
        int stok = Integer.parseInt(p.getProperty("pstok")) - cstok;
        txtstok.setText(String.valueOf(stok));
        txtjmljual.setEnabled(true);
        txtjmljual.requestFocus();
    }//GEN-LAST:event_cmdcrbrgMouseClicked

    private void cmdaddbrgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdaddbrgMouseClicked
        // TODO add your handling code here:
        int p = grdbrg.getRowCount(), i = 0, tanda = 0, jmlcolum = p + 1;
        ctotbyr = 0;
        for (int j = 0; j < p; j++) {
            if (txtkdbrg.getText().equals(grdbrg.getValueAt(j, 0).toString())) {
                jmlcolum -= 1;
            }
        }
        Object[][] data1 = new Object[jmlcolum][4];
        for (i = 0; i < p; i++) {
            data1[i][0] = grdbrg.getValueAt(i, 0).toString();
            data1[i][1] = grdbrg.getValueAt(i, 1).toString();
            data1[i][2] = grdbrg.getValueAt(i, 2).toString();
            if (txtkdbrg.getText().equals(grdbrg.getValueAt(i, 0).toString())) {
                int cjmljual = Integer.parseInt(grdbrg.getValueAt(i, 3).toString()) + Integer.parseInt(txtjmljual.getText());
                data1[i][3] = String.valueOf(cjmljual);
                tanda = 1;
            } else {
                data1[i][3] = grdbrg.getValueAt(i, 3).toString();
            }
            ctotbyr += (Integer.parseInt(grdbrg.getValueAt(i, 2).toString()) * Integer.parseInt(grdbrg.getValueAt(i, 3).toString()));
        }
        if (tanda == 0) {
            String tharga;
            data1[i][0] = txtkdbrg.getText();
            data1[i][1] = txtnmbrg.getText();
            tharga = txtharga.getText().substring(0, txtharga.getText().length() - 2);
            data1[i][2] = tharga;
            data1[i][3] = txtjmljual.getText();
            ctotbyr += (Integer.parseInt(tharga) * Integer.parseInt(txtjmljual.getText()));
        }
        final String[] headers = {"Kode Barang", "Nama Barang", "Harga", "Jumlah Jual"};
        grdbrg.setModel(new javax.swing.table.DefaultTableModel(data1, headers));
        txtkdbrg.setText("");
        txtnmbrg.setText("");
        txtharga.setText("");
        txtstok.setText("");
        txtjmljual.setText("");
        txtjmljual.setEnabled(false);
        NumberFormat numberFormatter = new DecimalFormat("#,###,###");
        String formattedNumber = numberFormatter.format(ctotbyr);
        txttotbyr.setText(formattedNumber);
        cmddelbrg.setEnabled(true);
        cmdaddbrg.setEnabled(false);
        cmdsimpan.setEnabled(true);
        cmdcrbrg.requestFocus();
    }//GEN-LAST:event_cmdaddbrgMouseClicked

    private void cmddelbrgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmddelbrgMouseClicked
        // TODO add your handling code here:
        if (grdbrg.isColumnSelected(0) == false && grdbrg.isColumnSelected(1) == false && grdbrg.isColumnSelected(2) == false
                && grdbrg.isColumnSelected(3) == false) {
            JOptionPane.showMessageDialog(this, "Silahkan pilih data terlebih dulu..!!", "Perintah", JOptionPane.WARNING_MESSAGE);
            return;
        } else {
            String ckdbrg = grdbrg.getValueAt(grdbrg.getSelectedRow(), 0).toString();
            int p = grdbrg.getRowCount(), i = 0, j = 0;
            Object[][] data1 = new Object[p - 1][4];
            while (i < p) {
                if (grdbrg.getValueAt(1, 0).toString().equals(ckdbrg) != true) {
                    i++;
                    data1[j][0] = grdbrg.getValueAt(1, 0).toString();
                    data1[j][1] = grdbrg.getValueAt(i, 1).toString();
                    data1[j][2] = grdbrg.getValueAt(1, 2).toString();
                    data1[j][3] = grdbrg.getValueAt(1, 3).toString();
                    j++;
                }
                i++;
            }
            final String[] headers = {"Kode Barang", "Nama Barang", "Harga", "Jumlah Jual"};
            grdbrg.setModel(new javax.swing.table.DefaultTableModel(data1, headers));
            p = grdbrg.getRowCount();
            if (p > 0) {
                cmddelbrg.setEnabled(true);
                cmdsimpan.setEnabled(true);
            } else {
                cmddelbrg.setEnabled(false);
                cmdsimpan.setEnabled(false);
            }
            ctotbyr = 0;
            for (i = 0; i < p; i++) {
            }
            ctotbyr += (Integer.parseInt(grdbrg.getValueAt(1, 2).toString())
                    * Integer.parseInt(grdbrg.getValueAt(1, 3).toString()));
            NumberFormat numberFormatter = new DecimalFormat("#,###.###");
            String formattedNumber = numberFormatter.format(ctotbyr);
            txttotbyr.setText(formattedNumber);
        }
    }//GEN-LAST:event_cmddelbrgMouseClicked

    private void txtjmljualFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtjmljualFocusGained
        // TODO add your handling code here:
        txtjmljual.setSelectionStart(0);
        txtjmljual.setSelectionEnd(txtharga.getText().length());
    }//GEN-LAST:event_txtjmljualFocusGained

    private void txtjmljualKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjmljualKeyReleased
        // TODO add your handling code here:
        try {
            if (Integer.parseInt(txtjmljual.getText()) > 0) {
                cmdaddbrg.setEnabled(true);
            } else {
                cmdaddbrg.setEnabled(false);
            }
        } catch (Exception e) {
            cmdaddbrg.setEnabled(false);
        }
    }//GEN-LAST:event_txtjmljualKeyReleased

    private void txtjmljualFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtjmljualFocusLost
        // TODO add your handling code here:
        if (Integer.parseInt(txtstok.getText()) < Integer.parseInt(txtjmljual.getText())) {
            JOptionPane.showMessageDialog(this, "Jumlah stok tidak mencukupi..!!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            txtjmljual.setText(txtstok.getText());
        }
    }//GEN-LAST:event_txtjmljualFocusLost

    private void opteditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opteditMouseClicked
        // TODO add your handling code here:
        cari_penjualan dialog = new cari_penjualan(new javax.swing.JFrame(), true);
        dialog.setVisible(true);
        Properties p = new Properties();
        try {
            FileInputStream in = new FileInputStream("penjualan.properties");
            p.load(in);
            in.close();
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        if (p.getProperty("pnotran").equals("0")) {
            bersih();
            return;
        }
        txtnotran.setText(p.getProperty("pnotran"));
        txttgltran.setText(p.getProperty("ptgltran"));
        txttotbyr.setText(p.getProperty("ptotbyr"));
        try {
            String sql = "select t1.kdbrg, t2.nmbrg, t2. harga, t1.jmljual " + "from tb_detail t1 inner join th_barang t2 on " + "t1.kdbrg=t2.kdbrg where notran=" + txtnotran.getText() + "";
            ResultSet rs = statement.executeQuery(sql);
            final String[] headers = {"Kode Barang", "Nama Barang", "Harga", "Jumlah Jual"};
            rs.last();
            int n = rs.getRow();
            Object[][] data = new Object[n][4];
            int i = 0;
            rs.beforeFirst();
            while (rs.next()) {
                data[i][0] = rs.getString(1);
                data[i][1] = rs.getString(2);
                data[i][2] = rs.getString(3);
                data[i][3] = rs.getString(4);
                i++;
            }
            grdbrg.setModel(new javax.swing.table.DefaultTableModel(data, headers));
        } catch (Exception DBException) {
            System.err.println("Error: " + DBException);
        }
        if (grdbrg.getRowCount() > 0) {
            cmddelbrg.setEnabled(true);
            cmdsimpan.setEnabled(true);
            cmdhapus.setEnabled(true);
        } else {
            cmddelbrg.setEnabled(false);
            cmdsimpan.setEnabled(false);
            cmdhapus.setEnabled(false);
        }
    }//GEN-LAST:event_opteditMouseClicked

    private void optbaruMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_optbaruMouseClicked
        // TODO add your handling code here:
        bersih();
    }//GEN-LAST:event_optbaruMouseClicked

    private void cmdhapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdhapusMouseClicked
        // TODO add your handling code here:
        if (cmdhapus.isEnabled() == false) {
            return;
        }
        try {
            String sql = "delete from tb_penjualan where notran='" + txtnotran.getText() + "'";
            statement.executeUpdate(sql);
            //Kembalikan stok semula
            sql = "select * from tb_detail";
            sql += " where notran='" + txtnotran.getText() + "'";
            ResultSet rs = statement.executeQuery(sql);
            int a = 0;
            rs.last();
            int n = rs.getRow();
            Object[][] tmprec = new Object[n][4];
            rs.beforeFirst();
            while (rs.next()) {
                tmprec[a][0] = rs.getString(1);
                tmprec[a][1] = rs.getString(2);
                tmprec[a][2] = rs.getString(3);
                tmprec[a][3] = rs.getString(4);
                a++;
            }
            for (int i = 0; i < n; i++) {
                sql = "update tb_barang set stok-stok+";
                sql += tmprec[i][2].toString() + " where kdbrg='";
                sql += tmprec[i][3].toString() + "'";
                statement.executeUpdate(sql);
            }
            //Kembalikan stok semula
            sql = "delete from tb_detail where notran='" + txtnotran.getText() + "'";
            statement.executeUpdate(sql);
            JOptionPane.showMessageDialog(this, "Hapus data Berhasil", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception DBException) {
            JOptionPane.showMessageDialog(this, "Hapus Data Gagal",
                    "Error", JOptionPane.ERROR_MESSAGE);
            System.err.println("Error: " + DBException);
        }
        bersih();
    }//GEN-LAST:event_cmdhapusMouseClicked

    private void cmdsimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cmdsimpanMouseClicked
        // TODO add your handling code here:
        if (cmdsimpan.isEnabled() == false) {
            return;
        }
        try {
            String sql;
            if (optbaru.isSelected()) {
                sql = "insert into tb_penjualan values('";
                sql += txtnotran.getText() + "','";
                sql += txttgltran.getText() + "',";
                sql += String.valueOf(ctotbyr) + ")";
                statement.executeUpdate(sql);
                int p = grdbrg.getRowCount();
                for (int i = 0; i < p; i++) {
                    sql = "insert into tb_detail (notran, kdbrg, jmljual) values ('";
                    sql += txtnotran.getText() + "', '";
                    sql += grdbrg.getValueAt(1, 0).toString() + "',";
                    sql += grdbrg.getValueAt(i, 3).toString() + ")";
                    statement.executeUpdate(sql);
                    //Kurangi Stok
                    sql = "update tb_barang set stok-stok-";
                    sql += grdbrg.getValueAt(1, 3).toString() + " where kdbrg='";
                    sql += grdbrg.getValueAt(1, 0).toString() + "'";
                    statement.executeUpdate(sql);
                    //Kurangi Stok
                }
            } else {
                sql = "update tb_penjualan set totbyr=";
                sql += String.valueOf(ctotbyr);
                sql += " where notran='" + txtnotran.getText() + "'";
                statement.executeUpdate(sql);
                //Kembalikan stok semula
                sql = "select * from tb_detail";
                sql += " where notran='" + txtnotran.getText() + "'";
                ResultSet rs = statement.executeQuery(sql);
                int a = 0;
                rs.last();
                int n = rs.getRow();
                Object[][] tmprec = new Object[n][4];
                rs.beforeFirst();
                while (rs.next()) {
                    tmprec[a][0] = rs.getString(1);
                    tmprec[a][1] = rs.getString(2);
                    tmprec[a][2] = rs.getString(3);
                    tmprec[a][3] = rs.getString(4);
                    a++;
                }
                for (int i = 0; i < n; i++) {
                    sql = "update tb_barang set stok-stok+";
                    sql += tmprec[i][2].toString() + " where kdbrg='";
                    sql += tmprec[i][3].toString() + "'";
                    statement.executeUpdate(sql);
                }
                //Kembalikan stok semula
                sql = "delete from tb_detail";
                sql += " where notran='" + txtnotran.getText() + "'";
                statement.executeUpdate(sql);
                int p = grdbrg.getRowCount();
                for (int i = 0; i < p; i++) {
                    sql = "insert into tb_detail (notran, kdbrg,jmljual) values ('";
                    sql += txtnotran.getText() + "', '";
                    sql += grdbrg.getValueAt(i, 0).toString() + "', ";
                    sql += grdbrg.getValueAt(i, 3).toString() + ")";
                    statement.executeUpdate(sql);
                    //Kurangi Stok
                    sql = "update tb_barang set stok-stok-";
                    sql += grdbrg.getValueAt(i, 3).toString() + " where kdbrg='";
                    sql += grdbrg.getValueAt(1, 0).toString() + "'";
                    statement.executeUpdate(sql);
                    //Kurangi Stok
                }
            }
            JOptionPane.showMessageDialog(this, "Simpan / Update Data Berhasil", "Informasi", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception DBException) {
            JOptionPane.showMessageDialog(this, "Simpan / Update Data Gagal",
                    "Error", JOptionPane.ERROR_MESSAGE);
            System.err.println("Error di Eksekusi : " + DBException);
        }
        bersih();
    }//GEN-LAST:event_cmdsimpanMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cmdaddbrg;
    private javax.swing.JButton cmdcrbrg;
    private javax.swing.JButton cmddelbrg;
    private javax.swing.JButton cmdhapus;
    private javax.swing.JButton cmdsimpan;
    private javax.swing.JTable grdbrg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton optbaru;
    private javax.swing.JRadioButton optedit;
    private javax.swing.JTextField txtharga;
    private javax.swing.JTextField txtjmljual;
    private javax.swing.JTextField txtkdbrg;
    private javax.swing.JTextField txtnmbrg;
    private javax.swing.JTextField txtnotran;
    private javax.swing.JTextField txtstok;
    private javax.swing.JTextField txttgltran;
    private javax.swing.JTextField txttotbyr;
    // End of variables declaration//GEN-END:variables
}
